version: '3.7'

services:
  croni:
    image: atareao/croni:v1.1
    restart: unless-stopped
    depends_on:
      - expertos
    networks:
      - internal
    volumes:
      - ./crontab:/crontab

  expertos:
    init: true
    image: atareao/expertos:v0.1.0
    volumes:
      - ./config.toml:/app/config.toml
    networks:
      - internal

networks:
  internal: {}

